<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Item;
use Illuminate\Database\Seeder;

class PricelistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Pricelist extracted from KB Supplier - Pricelist (10 April 2026).pdf
     */
    public function run(): void
    {
        // Create/Get Categories
        $catSayur = Category::firstOrCreate(['name' => 'Sayur'], ['is_active' => true]);
        $catBuah = Category::firstOrCreate(['name' => 'Buah'], ['is_active' => true]);
        $catDaging = Category::firstOrCreate(['name' => 'Daging'], ['is_active' => true]);
        $catGroceries = Category::firstOrCreate(['name' => 'Groceries'], ['is_active' => true]);
        $catBumbu = Category::firstOrCreate(['name' => 'Bumbu'], ['is_active' => true]);

        // SAYUR (Vegetables) - 154 items
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM001', 'name' => 'ANISTAR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM002', 'name' => 'ASAM JAWA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM003', 'name' => 'ASAM MUDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM006', 'name' => 'BABY KAILAN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM007', 'name' => 'BASIL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM008', 'name' => 'BAWANG BOMBAY', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM009', 'name' => 'BAWANG GORENG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM010', 'name' => 'BAWANG MERAH KUPAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM011', 'name' => 'BAWANG PUTIH KUPAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM012', 'name' => 'BAYAM JEPANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM013', 'name' => 'BAYAM LOKAL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM014', 'name' => 'BROCCOLI BATANG 3 JARI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM015', 'name' => 'BROCCOLI TANPA BATANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM016', 'name' => 'BUAH MELINJO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM017', 'name' => 'BUNCIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM018', 'name' => 'BUNCIS BABY', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM019', 'name' => 'BUNGA GENJER', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM020', 'name' => 'BUNGA PEPAYA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM021', 'name' => 'CABE HIJAU KERITING (PETIK)', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM022', 'name' => 'CABE HIJAU TANJUNG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM023', 'name' => 'CABE HIJAU TW (PETIK)', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM024', 'name' => 'CABE MERAH KERITING (PETIK)', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM025', 'name' => 'CABE MERAH TANJUNG PETIK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM026', 'name' => 'CABE MERAH TW (PETIK)', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM027', 'name' => 'CABE RAWIT HIJAU (PETIK)', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM028', 'name' => 'CABE RAWIT MERAH (PETIK)', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM030', 'name' => 'COMEO/CECIWIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM031', 'name' => 'DAUN BAWANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM032', 'name' => 'DAUN GENJER', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM033', 'name' => 'DAUN JERUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM034', 'name' => 'DAUN KEMANGI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM035', 'name' => 'DAUN KEMANGI', 'unit' => 'Ikat', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM037', 'name' => 'DAUN KUNYIT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM038', 'name' => 'DAUN MELINJO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM039', 'name' => 'DAUN MINT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM040', 'name' => 'DAUN PAKIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM041', 'name' => 'DAUN PANDAN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM042', 'name' => 'DAUN PANDAN', 'unit' => 'Ikat', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM043', 'name' => 'DAUN PEPAYA', 'unit' => 'Ikat', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM044', 'name' => 'DAUN PEPAYA JEPANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM045', 'name' => 'DAUN PISANG', 'unit' => 'Kompet', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM046', 'name' => 'DAUN SALAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM047', 'name' => 'DAUN SELEDRI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM048', 'name' => 'DAUN SINGKONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM049', 'name' => 'DAUN SINGKONG', 'unit' => 'Ikat', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM050', 'name' => 'EDAMAME', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM052', 'name' => 'HONJE/KECOMBRANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM053', 'name' => 'HUNKWE', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM054', 'name' => 'JAGUNG MANIS', 'unit' => 'Kaleng', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM055', 'name' => 'JAGUNG MANIS KUPAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM056', 'name' => 'JAGUNG SEMI KUPAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM057', 'name' => 'JAHE EMPRIT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM058', 'name' => 'JAHE GAJAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM059', 'name' => 'JAMUR ENOKI', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM060', 'name' => 'JAMUR KANCING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM061', 'name' => 'JAMUR KUPING KERING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM062', 'name' => 'JAMUR MERANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM063', 'name' => 'JAMUR SHINTAKE KERING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM064', 'name' => 'JAMUR TIRAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM065', 'name' => 'JENGKOL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM066', 'name' => 'JENGKOL MUDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM068', 'name' => 'KANGKUNG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM069', 'name' => 'KAPRI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM072', 'name' => 'KECAMBAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM073', 'name' => 'KECIPIR MUDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM074', 'name' => 'KEMBANG KOL BATANG 3 JARI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM075', 'name' => 'KEMBANG KOL TANPA BATANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM076', 'name' => 'KEMIRI UTUH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM077', 'name' => 'KENCUR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM078', 'name' => 'KENTANG BESAR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM079', 'name' => 'KENTANG DIENG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM080', 'name' => 'KENTANG RENDANG / SMALL POTATO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM083', 'name' => 'KICIWIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM084', 'name' => 'KOL PUTIH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM085', 'name' => 'KOL UNGU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM086', 'name' => 'KUNYIT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM087', 'name' => 'LABU ACAR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM088', 'name' => 'LABU PARANG / PUMPKIN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM089', 'name' => 'LABU SIAM BESAR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM090', 'name' => 'LABU SIAM KECIL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM096', 'name' => 'LENGKUAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM097', 'name' => 'LETTUCE', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM098', 'name' => 'LETTUCE LOLOROSA/RED', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM099', 'name' => 'LETTUCE ROMAINE LOKAL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM100', 'name' => 'LEUNCA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM101', 'name' => 'LOBAK PUTIH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM102', 'name' => 'ONCOM HITAM', 'unit' => 'Papan', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM103', 'name' => 'ONCOM MERAH', 'unit' => 'Papan', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM104', 'name' => 'OYONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM105', 'name' => 'PACAR CINA', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM106', 'name' => 'PAKCOY', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM107', 'name' => 'PAKCOY BABY', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM114', 'name' => 'PARIA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM115', 'name' => 'PETE', 'unit' => 'Papan', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM116', 'name' => 'POHPOHAN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM117', 'name' => 'REBUNG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM118', 'name' => 'SAWI HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM119', 'name' => 'SAWI PUTIH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM121', 'name' => 'SELADA KERITING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM122', 'name' => 'SEREH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM123', 'name' => 'SINGKONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM124', 'name' => 'SINGKONG MENTEGA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM132', 'name' => 'TALAS BOGOR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM133', 'name' => 'TAPE SINGKONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM134', 'name' => 'TAUGE', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM135', 'name' => 'TAUGE BANGKOK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM138', 'name' => 'TERONG HIJAU BULAT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM139', 'name' => 'TERONG UNGU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM140', 'name' => 'TESPONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM141', 'name' => 'TIMUN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM142', 'name' => 'TIMUN JEPANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM143', 'name' => 'TOMAT CHERRY', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM144', 'name' => 'TOMAT HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM145', 'name' => 'TOMAT MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM146', 'name' => 'TONGCAI', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM147', 'name' => 'UBI CILEMBU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM148', 'name' => 'UBI MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM149', 'name' => 'UBI PUTIH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM150', 'name' => 'UBI UNGU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM151', 'name' => 'WATER CHESNUT', 'unit' => 'Kaleng', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM152', 'name' => 'WORTEL IMPORT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM153', 'name' => 'WORTEL LOKAL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM154', 'name' => 'ZUCCHINNI GREEN', 'unit' => 'Kg', 'is_active' => true]);

        // GROCERIES - Items moved from SAYUR (Tahu, Tempe, Oncom)
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM125', 'name' => 'TAHU CINA', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM126', 'name' => 'TAHU KUNING/PUTIH BANDUNG', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM127', 'name' => 'TAHU PONG', 'unit' => 'Pcs', 'is_active' => true, 'notes' => 'Price: Rp 700 - Verify if correct']);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM128', 'name' => 'TAHU PUTIH', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM129', 'name' => 'TAHU PUTIH KECIL', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM130', 'name' => 'TAHU YUNYI', 'unit' => 'Bungkus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM131', 'name' => 'TAHU SEGITIGA', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM136', 'name' => 'TEMPE BUNGKUS DAUN', 'unit' => 'Papan', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM137', 'name' => 'TEMPE MENDOAN', 'unit' => 'Ikat', 'is_active' => true]);

        // GROCERIES - Original items (82 items)
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM155', 'name' => 'BAJIGUR ABAH BUBUK', 'unit' => 'Dus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM156', 'name' => 'BANDREX ABAH', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM157', 'name' => 'BERAS KETAN HITAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM158', 'name' => 'BERAS KETAN MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM159', 'name' => 'BERAS KETAN PUTIH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM160', 'name' => 'BERAS PANDAN WANGI 25 Kg', 'unit' => 'Ball', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM161', 'name' => 'BIHUN KERING', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM162', 'name' => 'CENDOL ELIZABETH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM164', 'name' => 'CINCAU HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM165', 'name' => 'CINCAU HITAM', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM166', 'name' => 'DURIAN PROZEN', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM167', 'name' => 'ESSEN MERAH KUPU-KUPU', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM168', 'name' => 'ESSEN PANDAN KUPU-KUPU', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM169', 'name' => 'GARAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM170', 'name' => 'GULA MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM171', 'name' => 'GULA MERAH', 'unit' => 'Bal', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM172', 'name' => 'GULA MERAH AREN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM173', 'name' => 'GULA PASIR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM174', 'name' => 'GULA PASIR', 'unit' => 'Bal', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM175', 'name' => 'GULA PUTIH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM177', 'name' => 'KACANG BOGOR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM178', 'name' => 'KACANG HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM179', 'name' => 'KACANG JOGO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM180', 'name' => 'KACANG KEDELAI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM181', 'name' => 'KACANG MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM182', 'name' => 'KACANG MERAH', 'unit' => 'Kaleng', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM184', 'name' => 'KACANG TANAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM185', 'name' => 'KACANG TANAH GILING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM186', 'name' => 'KACANG TANAH KUPAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM187', 'name' => 'KACANG TANAH REBUS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM188', 'name' => 'KACANG TOLO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM189', 'name' => 'KALDU JAMUR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM191', 'name' => 'KECAP MANIS KOMPAN', 'unit' => 'Jerigen', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM192', 'name' => 'KERUPUK BAWANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM193', 'name' => 'KERUPUK KRECEK MATANG', 'unit' => 'Bal', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM194', 'name' => 'KERUPUK TOROS', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM195', 'name' => 'KOLANG KALING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM196', 'name' => 'KOPI BUBUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM198', 'name' => 'KULIT LUMPIA BAROKAH', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM199', 'name' => 'KULIT PANGSIT', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM200', 'name' => 'KULIT PANGSIT AA Pack 50 PCS', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM201', 'name' => 'KUNYIT BUBUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM202', 'name' => 'KUNYIT GILING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM203', 'name' => 'KURMA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM204', 'name' => 'KWETIAU @500GR', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM205', 'name' => 'LECI', 'unit' => 'Kaleng', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM206', 'name' => 'MARJAN COCO PANDAN', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM207', 'name' => 'MARJAN COCO PANDAN', 'unit' => 'Dus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM208', 'name' => 'MARJAN MELON', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM209', 'name' => 'MENTEGA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM210', 'name' => 'MIE AYAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM211', 'name' => 'MIE KUNING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM212', 'name' => 'MINYAK GORENG 18LTR', 'unit' => 'Liter', 'is_active' => true, 'notes' => 'Corrected unit from Kg to Liter']);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM213', 'name' => 'MINYAK WIJEN', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM214', 'name' => 'MSG/SASA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM217', 'name' => 'ROTI TAWAR', 'unit' => 'Bungkus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM218', 'name' => 'ROYCO AYAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM219', 'name' => 'ROYCO AYAM', 'unit' => 'Dus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM220', 'name' => 'ROYCO SAPI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM221', 'name' => 'SANTAN CAIR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM222', 'name' => 'SANTAN KARA', 'unit' => 'Liter', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM223', 'name' => 'SANTAN KARA', 'unit' => 'Dus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM224', 'name' => 'SAOS TIRAM', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM225', 'name' => 'SIRUP LECI NIKI SARI', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM226', 'name' => 'SIRUP MARJAN LECI', 'unit' => 'Botol', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM227', 'name' => 'SKM (SUSU KENTAL MANIS)', 'unit' => 'Kaleng', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM228', 'name' => 'TEH LIPTON', 'unit' => 'Dus', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM229', 'name' => 'TEPUNG MAIZENA', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM230', 'name' => 'TEPUNG TAPIOKA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM231', 'name' => 'TEPUNG TERIGU SEGITIGA BIRU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catGroceries->id, 'code' => 'ITM234', 'name' => 'TUSUK SATE', 'unit' => 'Pack', 'is_active' => true]);

        // BUMBU (Spices) - Items recategorized from SAYUR
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM029', 'name' => 'CENGKEH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM036', 'name' => 'DAUN KETUMBAR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM070', 'name' => 'KAYU MANIS STICK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM071', 'name' => 'KAYU MANIS UTUH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM081', 'name' => 'KETUMBAR BIJI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM082', 'name' => 'KETUMBAR BUBUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM091', 'name' => 'LADA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM092', 'name' => 'LADA HITAM BUBUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM093', 'name' => 'LADA HITAM WHOLE', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM094', 'name' => 'LADA PUTIH BUBUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM095', 'name' => 'LADA PUTIH WHOLE', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM108', 'name' => 'PALA BIJI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM109', 'name' => 'PALA BUBUK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM111', 'name' => 'PAPRIKA HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM112', 'name' => 'PAPRIKA KUNING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM113', 'name' => 'PAPRIKA MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM120', 'name' => 'SEDAP MALAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM176', 'name' => 'JINTEN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM190', 'name' => 'KAPULAGA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM232', 'name' => 'TERASI MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM233', 'name' => 'TERASI UDANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBumbu->id, 'code' => 'ITM235', 'name' => 'VANILI BUBUK KUPU-KUPU', 'unit' => 'Botol', 'is_active' => true]);

        // SAYUR - Items moved FROM GROCERIES (Fresh vegetables)
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM183', 'name' => 'KACANG PANJANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM197', 'name' => 'KUCAI', 'unit' => 'Ikat', 'is_active' => true]);
        Item::create(['category_id' => $catSayur->id, 'code' => 'ITM216', 'name' => 'PETERSELI', 'unit' => 'Kg', 'is_active' => true]);

        // DAGING (Meat/Protein/Seafood) - 24 items
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM236', 'name' => 'AYAM TG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM237', 'name' => 'BABAT SAPI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM238', 'name' => 'BABY NILA', 'unit' => 'Pack', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM239', 'name' => 'BEBEK', 'unit' => 'Ekor', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM240', 'name' => 'CUMI DAGING BASAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM241', 'name' => 'CUMI SOTONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM242', 'name' => 'GANDIK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM243', 'name' => 'GURAME', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM244', 'name' => 'IKAN ASIN PEDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM245', 'name' => 'IKAN MAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM246', 'name' => 'IKAN NILA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM247', 'name' => 'IKAN TERI TAWAR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM248', 'name' => 'IKAN TERI MEDAN SUPER', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM249', 'name' => 'JANDO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM250', 'name' => 'KIKIL TEBAL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM251', 'name' => 'KIKIL TIPIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM252', 'name' => 'LIMPA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM253', 'name' => 'PARU SAPI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM254', 'name' => 'AYAM PEJANTAN', 'unit' => 'Ekor', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM255', 'name' => 'SENGKEL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM256', 'name' => 'TELOR ASIN', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM257', 'name' => 'TELOR AYAM', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM258', 'name' => 'TELOR PUYUH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM259', 'name' => 'UDANG WINDU (ISI 20-25)', 'unit' => 'Kg', 'is_active' => true]);

        // Also add OTAK-OTAK to DAGING (moved from GROCERIES)
        Item::create(['category_id' => $catDaging->id, 'code' => 'ITM215', 'name' => 'OTAK-OTAK', 'unit' => 'Pack', 'is_active' => true]);

        // BUAH (Fruits) - 48 items
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM260', 'name' => 'ALPUKAT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM261', 'name' => 'ANGGUR HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM262', 'name' => 'ANGGUR MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM263', 'name' => 'APEL MALANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM264', 'name' => 'APPLE GREEN IMPORT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM265', 'name' => 'APPLE RED IMPORT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM266', 'name' => 'BELIMBING SAYUR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM267', 'name' => 'BENGKOANG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM268', 'name' => 'JAMBU AIR', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM269', 'name' => 'JAMBU BATU MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM270', 'name' => 'JERUK LEMON IMPORT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM271', 'name' => 'JERUK LEMON LOKAL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM272', 'name' => 'JERUK LIMO', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM273', 'name' => 'JERUK MEDAN', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM274', 'name' => 'JERUK NIPIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM275', 'name' => 'JERUK PERAS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM276', 'name' => 'JERUK SUNKIST', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM277', 'name' => 'KEDONDONG', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM278', 'name' => 'KELAPA KOPYOR', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM279', 'name' => 'KELAPA KOPYOR KELAS B', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM280', 'name' => 'KELAPA MUDA', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM281', 'name' => 'KELAPA MUDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM282', 'name' => 'KELAPA PARUT', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM283', 'name' => 'KELAPA PARUT', 'unit' => 'Biji', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM284', 'name' => 'KIWI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM285', 'name' => 'MANGGA GOLEK', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM286', 'name' => 'MANGGA HARUM MANIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM287', 'name' => 'MANGGA MUDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM288', 'name' => 'MANGGIS', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM289', 'name' => 'MELON KUNING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM290', 'name' => 'MELON HIJAU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM291', 'name' => 'NANAS MADU', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM292', 'name' => 'NANAS UTUH LOKAL', 'unit' => 'Pcs', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM293', 'name' => 'NANGKA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM294', 'name' => 'NANGKA MUDA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM295', 'name' => 'PEAR KUNING LOKAL', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM296', 'name' => 'PEAR XIANGLI', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM297', 'name' => 'PEPAYA CALIFORNIA', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM298', 'name' => 'PISANG AMBON', 'unit' => 'Sisir', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM299', 'name' => 'PISANG KEPOK', 'unit' => 'Sisir', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM300', 'name' => 'PISANG LAMPUNG', 'unit' => 'Sisir', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM301', 'name' => 'PISANG MAS', 'unit' => 'Sisir', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM302', 'name' => 'PISANG TANDUK', 'unit' => 'Sisir', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM303', 'name' => 'PISANG ULI', 'unit' => 'Sisir', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM304', 'name' => 'SALAK PONDOH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM305', 'name' => 'SEMANGKA KUNING', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM306', 'name' => 'SEMANGKA MERAH', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM307', 'name' => 'STRAWBERRY', 'unit' => 'Kg', 'is_active' => true]);
        Item::create(['category_id' => $catBuah->id, 'code' => 'ITM308', 'name' => 'STRAWBERRY', 'unit' => 'Pack', 'is_active' => true]);
    }
}
